import type { FamiliaCor, Produto, Variante } from "../tipos";

/*
 * Catálogo provisório da apresentação. Sem fotos: o site desenha cada boné com
 * a cor da variante. Para usar fotos reais, basta preencher `imagens`.
 */

function cor(
  id: string,
  nome: string,
  familia: FamiliaCor,
  hex: string,
  extra: Partial<Variante> = {},
): Variante {
  return { id, cor: nome, familia, hex, imagens: [], disponivel: true, ...extra };
}

export const produtos: Produto[] = [
  {
    id: "ne-9forty-essential",
    slug: "new-era-9forty-essential",
    nome: "9FORTY Essential",
    marcaId: "new-era",
    categoriaId: "aba-curva",
    aba: "curva",
    fechamento: "strapback",
    descricaoCurta: "Copa estruturada de seis gomos e regulagem traseira em metal.",
    preco: 189.9,
    status: "ativo",
    destaque: true,
    novo: false,
    ordem: 1,
    variantes: [
      cor("preto", "Preto", "preto", "#1d1d1f", { codigo: "NE940-PT" }),
      cor("off-white", "Off-white", "off-white", "#eee9df", { codigo: "NE940-OW" }),
      cor("marinho", "Azul-marinho", "azul", "#25324a", { codigo: "NE940-AZ" }),
    ],
  },
  {
    id: "ne-9fifty-original",
    slug: "new-era-9fifty-original-fit",
    nome: "9FIFTY Original Fit",
    marcaId: "new-era",
    categoriaId: "aba-reta",
    aba: "reta",
    fechamento: "snapback",
    descricaoCurta: "Aba reta, frente alta e fecho snapback.",
    preco: 229.9,
    status: "ativo",
    destaque: false,
    novo: true,
    ordem: 2,
    variantes: [
      cor("grafite", "Grafite", "cinza", "#4a4b50", { codigo: "NE950-GF" }),
      cor("preto", "Preto", "preto", "#1d1d1f", { codigo: "NE950-PT" }),
    ],
  },
  {
    id: "ne-59fifty-classic",
    slug: "new-era-59fifty-classic",
    nome: "59FIFTY Classic",
    marcaId: "new-era",
    categoriaId: "aba-reta",
    aba: "reta",
    fechamento: "fitted",
    descricaoCurta: "Fechado, sem regulagem. Escolha pelo tamanho.",
    preco: 299.9,
    status: "ativo",
    destaque: false,
    novo: false,
    ordem: 3,
    variantes: [
      cor("vermelho", "Vermelho", "vermelho", "#8e2a2a", { codigo: "NE5950-VM" }),
      cor("preto", "Preto", "preto", "#1d1d1f", { codigo: "NE5950-PT" }),
    ],
  },
  {
    id: "nike-club",
    slug: "nike-club-cap",
    nome: "Club Cap",
    marcaId: "nike",
    categoriaId: "aba-curva",
    aba: "curva",
    fechamento: "strapback",
    descricaoCurta: "Sarja de algodão e ajuste com fivela.",
    preco: 149.9,
    precoPromocional: 129.9,
    status: "ativo",
    destaque: true,
    novo: false,
    ordem: 4,
    variantes: [
      cor("branco", "Branco", "branco", "#f7f6f2", { codigo: "NK-CLB-BR" }),
      cor("preto", "Preto", "preto", "#1d1d1f", { codigo: "NK-CLB-PT" }),
      cor("bege", "Bege", "bege", "#cdbb9c", { codigo: "NK-CLB-BG" }),
    ],
  },
  {
    id: "nike-featherlight",
    slug: "nike-featherlight",
    nome: "Featherlight",
    marcaId: "nike",
    categoriaId: "dad-hat",
    aba: "curva",
    fechamento: "strapback",
    descricaoCurta: "Copa macia e tecido leve, que seca rápido.",
    preco: 169.9,
    status: "ativo",
    destaque: false,
    novo: false,
    ordem: 5,
    variantes: [
      cor("azul", "Azul", "azul", "#2f4f7a", { codigo: "NK-FTL-AZ" }),
      cor("verde", "Verde-oliva", "verde", "#5a6748", { codigo: "NK-FTL-VD" }),
    ],
  },
  {
    id: "oakley-b1b",
    slug: "oakley-trucker-b1b",
    nome: "Trucker B1B",
    marcaId: "oakley",
    categoriaId: "trucker",
    aba: "curva",
    fechamento: "snapback",
    descricaoCurta: "Frente em espuma e tela traseira respirável.",
    preco: 179.9,
    status: "ativo",
    destaque: false,
    novo: true,
    ordem: 6,
    variantes: [
      cor("branco-preto", "Branco e preto", "branco", "#f2efe8", {
        hexSecundario: "#1d1d1f",
        codigo: "OK-B1B-BP",
      }),
      cor("marrom", "Marrom e areia", "marrom", "#7a5b3c", {
        hexSecundario: "#d8cfbf",
        codigo: "OK-B1B-MA",
      }),
    ],
  },
  {
    id: "oakley-tincan",
    slug: "oakley-tincan",
    nome: "Tincan",
    marcaId: "oakley",
    categoriaId: "trucker",
    aba: "reta",
    fechamento: "snapback",
    descricaoCurta: "Trucker de aba reta com tela traseira.",
    preco: 219.9,
    status: "ativo",
    destaque: false,
    novo: false,
    ordem: 7,
    variantes: [
      cor("preto", "Preto e cinza", "preto", "#1d1d1f", {
        hexSecundario: "#8d8e92",
        codigo: "OK-TIN-PC",
      }),
    ],
  },
  {
    id: "lacoste-sport",
    slug: "lacoste-dad-hat-sport",
    nome: "Dad Hat Sport",
    marcaId: "lacoste",
    categoriaId: "dad-hat",
    aba: "curva",
    fechamento: "strapback",
    descricaoCurta: "Piquê de algodão e copa desestruturada.",
    preco: 259.9,
    status: "ativo",
    destaque: true,
    novo: false,
    ordem: 8,
    variantes: [
      cor("off-white", "Off-white", "off-white", "#efebe2", { codigo: "LC-DAD-OW" }),
      cor("verde", "Verde", "verde", "#2f5a45", { codigo: "LC-DAD-VD" }),
      cor("marinho", "Azul-marinho", "azul", "#22304a", { codigo: "LC-DAD-AZ" }),
    ],
  },
  {
    id: "lacoste-classic",
    slug: "lacoste-classic",
    nome: "Classic",
    marcaId: "lacoste",
    categoriaId: "aba-curva",
    aba: "curva",
    fechamento: "strapback",
    descricaoCurta: "Sarja encorpada e fivela metálica.",
    preco: 279.9,
    status: "esgotado",
    destaque: false,
    novo: false,
    ordem: 9,
    variantes: [cor("preto", "Preto", "preto", "#1d1d1f", { codigo: "LC-CLS-PT", disponivel: false })],
  },
  {
    id: "puma-archive",
    slug: "puma-archive",
    nome: "Archive",
    marcaId: "puma",
    categoriaId: "dad-hat",
    aba: "curva",
    fechamento: "strapback",
    descricaoCurta: "Algodão lavado e ajuste com fivela.",
    preco: 119.9,
    status: "ativo",
    destaque: false,
    novo: false,
    ordem: 10,
    variantes: [
      cor("bege", "Bege", "bege", "#c9b796", { codigo: "PM-ARC-BG" }),
      cor("preto", "Preto", "preto", "#1d1d1f", { codigo: "PM-ARC-PT" }),
    ],
  },
  {
    id: "puma-trucker",
    slug: "puma-trucker",
    nome: "Trucker Street",
    marcaId: "puma",
    categoriaId: "trucker",
    aba: "curva",
    fechamento: "snapback",
    descricaoCurta: "Tela traseira e frente estruturada.",
    preco: 139.9,
    precoPromocional: 109.9,
    status: "ativo",
    destaque: false,
    novo: false,
    ordem: 11,
    variantes: [
      cor("cinza", "Cinza e preto", "cinza", "#8a8b8f", {
        hexSecundario: "#1d1d1f",
        codigo: "PM-TRK-CP",
      }),
    ],
  },
  {
    id: "ne-9twenty-washed",
    slug: "new-era-9twenty-washed",
    nome: "9TWENTY Washed",
    marcaId: "new-era",
    categoriaId: "dad-hat",
    aba: "curva",
    fechamento: "strapback",
    descricaoCurta: "Algodão lavado, toque macio e ajuste com fivela.",
    preco: 169.9,
    status: "ativo",
    destaque: false,
    novo: true,
    ordem: 12,
    variantes: [
      cor("marrom", "Marrom", "marrom", "#6b4f37", { codigo: "NE920-MR" }),
      cor("cinza", "Cinza", "cinza", "#6f7075", { codigo: "NE920-CZ" }),
    ],
  },
  {
    id: "nike-pro-flat",
    slug: "nike-pro-flat",
    nome: "Pro Flat",
    marcaId: "nike",
    categoriaId: "aba-reta",
    aba: "reta",
    fechamento: "snapback",
    descricaoCurta: "Aba reta e frente estruturada.",
    preco: 189.9,
    status: "ativo",
    destaque: false,
    novo: false,
    ordem: 13,
    variantes: [
      cor("verde", "Verde-militar", "verde", "#4b5340", { codigo: "NK-PRO-VM" }),
      cor("preto", "Preto", "preto", "#1d1d1f", { codigo: "NK-PRO-PT" }),
    ],
  },
  {
    id: "oakley-ellipse",
    slug: "oakley-ellipse",
    nome: "Ellipse",
    marcaId: "oakley",
    categoriaId: "aba-curva",
    aba: "curva",
    fechamento: "strapback",
    descricaoCurta: "Copa média e acabamento fosco.",
    preco: 199.9,
    status: "ativo",
    destaque: false,
    novo: false,
    ordem: 14,
    variantes: [
      cor("off-white", "Off-white", "off-white", "#ece7dc", { codigo: "OK-ELP-OW" }),
      cor("marrom", "Marrom", "marrom", "#5e4632", { codigo: "OK-ELP-MR" }),
    ],
  },
];
